import { FoodDetailsProps } from "./interface";

export const dummyFoodData: FoodDetailsProps[] = [
{
    name: 'Apple',
    imageUrl: 'https://example.com/apple.jpg',
    daysLeft: 5,
    location: 'Fridge',
    expiryDate: '01/25/2024',
    reminder: '1 Day Before Exp',
    category: 'Fruit',
    others: 'None',
    storageTips: 'Store in a cool, dry place.',
    quantity: 10,
},
{
    name: 'Banana',
    imageUrl: 'https://example.com/banana.jpg',
    daysLeft: 3,
    location: 'Fridge',
    expiryDate: '01/23/2024',
    reminder: '2 Days Before Exp',
    category: 'Fruit',
    others: 'Keep at room temperature until ripe.',
    storageTips: 'Do not refrigerate until ripe.',
    quantity: 6,
},
{
    name: 'Carrot',
    imageUrl: 'https://example.com/carrot.jpg',
    daysLeft: 10,
    location: 'Fridge',
    expiryDate: '02/01/2024',
    reminder: '3 Days Before Exp',
    category: 'Vegetable',
    others: 'Remove tops for longer storage.',
    storageTips: 'Store in a plastic bag in the fridge.',
    quantity: 12,
},
{
    name: 'Broccoli',
    imageUrl: 'https://example.com/broccoli.jpg',
    daysLeft: 7,
    location: 'Fridge',
    expiryDate: '01/28/2024',
    reminder: '2 Days Before Exp',
    category: 'Vegetable',
    others: 'Keep in a loose plastic bag.',
    storageTips: 'Store in the fridge crisper drawer.',
    quantity: 4,
},
{
    name: 'Chicken Breast',
    imageUrl: 'https://example.com/chicken.jpg',
    daysLeft: 2,
    location: 'Freezer',
    expiryDate: '03/01/2024',
    reminder: '5 Days Before Exp',
    category: 'Meat',
    others: 'Defrost in the fridge overnight.',
    storageTips: 'Store in an airtight container in the freezer.',
    quantity: 8,
},
{
    name: 'Salmon Fillet',
    imageUrl: 'https://example.com/salmon.jpg',
    daysLeft: 4,
    location: 'Freezer',
    expiryDate: '03/05/2024',
    reminder: '7 Days Before Exp',
    category: 'Meat',
    others: 'Cook thoroughly before eating.',
    storageTips: 'Store in an airtight container in the freezer.',
    quantity: 5,
},
{
    name: 'Milk',
    imageUrl: 'https://example.com/milk.jpg',
    daysLeft: 8,
    location: 'Fridge',
    expiryDate: '01/29/2024',
    reminder: '2 Days Before Exp',
    category: 'Dairy',
    others: 'Keep sealed after opening.',
    storageTips: 'Store in the fridge door.',
    quantity: 2,
},
{
    name: 'Yogurt',
    imageUrl: 'https://example.com/yogurt.jpg',
    daysLeft: 6,
    location: 'Fridge',
    expiryDate: '01/27/2024',
    reminder: '3 Days Before Exp',
    category: 'Dairy',
    others: 'Consume after opening within 7 days.',
    storageTips: 'Store in the fridge.',
    quantity: 8,
},
{
    name: 'Cheddar Cheese',
    imageUrl: 'https://example.com/cheese.jpg',
    daysLeft: 14,
    location: 'Fridge',
    expiryDate: '02/07/2024',
    reminder: '5 Days Before Exp',
    category: 'Dairy',
    others: 'Wrap in wax paper and store in a sealed container.',
    storageTips: 'Store in the fridge cheese drawer.',
    quantity: 3,
},
{
    name: 'Eggplant',
    imageUrl: 'https://example.com/eggplant.jpg',
    daysLeft: 7,
    location: 'Pantry',
    expiryDate: '01/30/2024',
    reminder: '2 Days Before Exp',
    category: 'Vegetable',
    others: 'Store in a cool, dry place.',
    storageTips: 'Do not refrigerate.',
    quantity: 5,
},
{
    name: 'Cucumber',
    imageUrl: 'https://example.com/cucumber.jpg',
    daysLeft: 4,
    location: 'Fridge',
    expiryDate: '01/26/2024',
    reminder: '1 Day Before Exp',
    category: 'Vegetable',
    others: 'Wrap in a paper towel before storing.',
    storageTips: 'Store in the fridge crisper drawer.',
    quantity: 10,
},
{
    name: 'Tomato',
    imageUrl: 'https://example.com/tomato.jpg',
    daysLeft: 3,
    location: 'Pantry',
    expiryDate: '01/24/2024',
    reminder: '1 Day Before Exp',
    category: 'Vegetable',
    others: 'Keep at room temperature until ripe.',
    storageTips: 'Do not refrigerate until ripe.',
    quantity: 12,
},
{
    name: 'Orange Juice',
    imageUrl: 'https://example.com/orangejuice.jpg',
    daysLeft: 5,
    location: 'Fridge',
    expiryDate: '01/25/2024',
    reminder: '2 Days Before Exp',
    category: 'Dairy',
    others: 'Shake well before consuming.',
    storageTips: 'Store in the fridge door.',
    quantity: 3,
},
{
    name: 'Butter',
    imageUrl: 'https://example.com/butter.jpg',
    daysLeft: 12,
    location: 'Fridge',
    expiryDate: '02/05/2024',
    reminder: '3 Days Before Exp',
    category: 'Dairy',
    others: 'Keep covered when not in use.',
    storageTips: 'Store in the fridge butter compartment.',
    quantity: 4,
},
{
    name: 'Spinach',
    imageUrl: 'https://example.com/spinach.jpg',
    daysLeft: 2,
    location: 'Fridge',
    expiryDate: '01/23/2024',
    reminder: '1 Day Before Exp',
    category: 'Vegetable',
    others: 'Wash before eating.',
    storageTips: 'Store in a plastic bag in the fridge.',
    quantity: 6,
},
{
    name: 'Avocado',
    imageUrl: 'https://example.com/avocado.jpg',
    daysLeft: 1,
    location: 'Pantry',
    expiryDate: '01/22/2024',
    reminder: '1 Day Before Exp',
    category: 'Fruit',
    others: 'Keep at room temperature until ripe.',
    storageTips: 'Do not refrigerate until ripe.',
    quantity: 4,
},
{
    name: 'Pasta',
    imageUrl: 'https://example.com/pasta.jpg',
    daysLeft: 90,
    location: 'Pantry',
    expiryDate: '04/20/2024',
    reminder: '7 Days Before Exp',
    category: 'Other',
    others: 'Store in an airtight container.',
    storageTips: 'Keep in a cool, dry place.',
    quantity: 5,
},
{
    name: 'Rice',
    imageUrl: 'https://example.com/rice.jpg',
    daysLeft: 180,
    location: 'Pantry',
    expiryDate: '07/20/2024',
    reminder: '14 Days Before Exp',
    category: 'Other',
    others: 'Store in an airtight container.',
    storageTips: 'Keep in a cool, dry place.',
    quantity: 20,
},
{
    name: 'Lettuce',
    imageUrl: 'https://example.com/lettuce.jpg',
    daysLeft: 3,
    location: 'Fridge',
    expiryDate: '01/24/2024',
    reminder: '1 Day Before Exp',
    category: 'Vegetable',
    others: 'Rinse before use.',
    storageTips: 'Store in the fridge crisper drawer.',
    quantity: 4,
},
{
    name: 'Bell Pepper',
    imageUrl: 'https://example.com/bellpepper.jpg',
    daysLeft: 5,
    location: 'Fridge',
    expiryDate: '01/26/2024',
    reminder: '2 Days Before Exp',
    category: 'Vegetable',
    others: 'Store in a plastic bag.',
    storageTips: 'Keep in the fridge crisper drawer.',
    quantity: 6,
},
{
    name: 'Ground Beef',
    imageUrl: 'https://example.com/groundbeef.jpg',
    daysLeft: 3,
    location: 'Freezer',
    expiryDate: '03/20/2024',
    reminder: '5 Days Before Exp',
    category: 'Meat',
    others: 'Defrost in the fridge before cooking.',
    storageTips: 'Store in an airtight container in the freezer.',
    quantity: 2,
},
{
    name: 'Grapes',
    imageUrl: 'https://example.com/grapes.jpg',
    daysLeft: 7,
    location: 'Fridge',
    expiryDate: '01/30/2024',
    reminder: '2 Days Before Exp',
    category: 'Fruit',
    others: 'Rinse before eating.',
    storageTips: 'Store in the fridge crisper drawer.',
    quantity: 25,
},
{
    name: 'Blueberries',
    imageUrl: 'https://example.com/blueberries.jpg',
    daysLeft: 5,
    location: 'Fridge',
    expiryDate: '01/25/2024',
    reminder: '1 Day Before Exp',
    category: 'Fruit',
    others: 'Rinse before eating.',
    storageTips: 'Store in the fridge crisper drawer.',
    quantity: 20,
},
{
    name: 'Sour Cream',
    imageUrl: 'https://example.com/sourcream.jpg',
    daysLeft: 10,
    location: 'Fridge',
    expiryDate: '02/01/2024',
    reminder: '3 Days Before Exp',
    category: 'Dairy',
    others: 'Keep sealed after opening.',
    storageTips: 'Store in the fridge.',
    quantity: 3,
},
{
    name: 'Bacon',
    imageUrl: 'https://example.com/bacon.jpg',
    daysLeft: 4,
    location: 'Freezer',
    expiryDate: '03/05/2024',
    reminder: '5 Days Before Exp',
    category: 'Meat',
    others: 'Cook thoroughly before eating.',
    storageTips: 'Store in an airtight container in the freezer.',
    quantity: 5,
},
{
    name: 'Oranges',
    imageUrl: 'https://example.com/oranges.jpg',
    daysLeft: 12,
    location: 'Pantry',
    expiryDate: '02/05/2024',
    reminder: '3 Days Before Exp',
    category: 'Fruit',
    others: 'Peel before eating.',
    storageTips: 'Store in a cool, dry place.',
    quantity: 8,
},
{
    name: 'Pineapple',
    imageUrl: 'https://example.com/pineapple.jpg',
    daysLeft: 5,
    location: 'Pantry',
    expiryDate: '01/25/2024',
    reminder: '2 Days Before Exp',
    category: 'Fruit',
    others: 'Cut into slices before eating.',
    storageTips: 'Keep at room temperature until ripe.',
    quantity: 2,
},
{
    name: 'Zucchini',
    imageUrl: 'https://example.com/zucchini.jpg',
    daysLeft: 6,
    location: 'Fridge',
    expiryDate: '01/27/2024',
    reminder: '2 Days Before Exp',
    category: 'Vegetable',
    others: 'Rinse before cooking.',
    storageTips: 'Store in the fridge crisper drawer.',
    quantity: 6,
},
{
    name: 'Strawberries',
    imageUrl: 'https://example.com/strawberries.jpg',
    daysLeft: 4,
    location: 'Fridge',
    expiryDate: '01/26/2024',
    reminder: '1 Day Before Exp',
    category: 'Fruit',
    others: 'Rinse before eating.',
    storageTips: 'Store in the fridge crisper drawer.',
    quantity: 15,
},
{
    name: 'Cabbage',
    imageUrl: 'https://example.com/cabbage.jpg',
    daysLeft: 9,
    location: 'Fridge',
    expiryDate: '02/01/2024',
    reminder: '2 Days Before Exp',
    category: 'Vegetable',
    others: 'Rinse before cooking.',
    storageTips: 'Store in the fridge crisper drawer.',
    quantity: 3,
},
{
    name: 'Peanut Butter',
    imageUrl: 'https://example.com/peanutbutter.jpg',
    daysLeft: 365,
    location: 'Pantry',
    expiryDate: '12/31/2024',
    reminder: '30 Days Before Exp',
    category: 'Other',
    others: 'Keep tightly sealed when not in use.',
    storageTips: 'Store in a cool, dry place.',
    quantity: 1,
},
];
